services:
  honeypot:
    image: antoniolara2000/honeypotia:latest
    container_name: opencanary_latest
    restart: unless-stopped
    volumes:
      - /mnt/AI-DATA/alara/CiberIA_O1_A3/honeypot/data/.opencanary.conf:/root/.opencanary.conf
    ports:
      - "80:80"
