services:
  honeypot:
    container_name: opencanary_latest
    build:
      context: .
    restart: unless-stopped
    volumes:
      - /mnt/AI-DATA/alara/CiberIA_O1_A3/honeypot/data/.opencanary.conf:/root/.opencanary.conf
      - /mnt/AI-DATA/alara/CiberIA_O1_A3/honeypot/fine_tuning/prompts:/app/prompts
    ports:
      - "80:80"
